import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./../components/Footer.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="app-wrapper">
          <meta name="viewport" content="width=1280, user-scalable=no" />
          <main style={{ minHeight: "60vh", background: "#fff" }} />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
